### ISSUE TITLE
Missing :endif: for a single line if statement with multiple |s

### ISSUE THREAD

**Issue by moll** [Kuniwak/vint#148]
Hey,

Is it me or does this trip up vimlparser? 
```vim
if exists("l:last") | close | wincmd p | endif
```

Throws:
```
split.vim:44:1: E171: Missing :endif:    ENDFUNCTION (see ynkdir/vim-vimlparser)
```

**Comment by Kuniwak** [comment]
Hi, @moll.
Sorry for my late reply.

This problem was resolved on v0.3.6.
Please update Vint and try it.

**Comment by moll** [comment]
Thanks. I'll report back if it's still not working once I get around to it. I'll close this issue till then.

**Comment by lukelbd** [comment]
Just discovered this is still an issue when using *user commands* within the `if | ... | endif` block (and possibly other esoteric situations?).

For example:

```vim
if 1 | echo "bar" | endif  " linter correctly identifies endif
if 1 | Foo "bar" | endif  " linter fails to identify endif
```

The error I get is `.vimrc|1512 error| E171: Missing :endif:    TOPLEVEL (SyntaxError)`. It causes the linter to ignore the whole file because it thinks it's within the unterminated `if` statement.

This issue should probably be reopened. (Really awesome project btw -- thanks for making it!)
